common_pkgs:
  pkg:
    - installed
    - refresh: True
    - pkgs:
      - patch
      - curl
      - debconf
      - gcc
      - ethtool
      - strace
      - screen
      - tmux
      - python-pip
      - python-setuptools
      - python-netifaces
      - sqlite3
      - traceroute
      - python-dev
      - build-essential
      - libffi-dev
